HW_1
================
nr2774
2022-09-22

# Problem_1

``` r
#Loading in relevant packages. 
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6     ✔ purrr   0.3.4
    ## ✔ tibble  3.1.8     ✔ dplyr   1.0.9
    ## ✔ tidyr   1.2.0     ✔ stringr 1.4.1
    ## ✔ readr   2.1.2     ✔ forcats 0.5.2
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
# Discription of the dataset 

data("penguins", package = "palmerpenguins")
penguins
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
    ##    <fct>   <fct>              <dbl>         <dbl>      <int>   <int> <fct> <int>
    ##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
    ##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
    ##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
    ##  4 Adelie  Torgersen           NA            NA           NA      NA <NA>   2007
    ##  5 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
    ##  6 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
    ##  7 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
    ##  8 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
    ##  9 Adelie  Torgersen           34.1          18.1        193    3475 <NA>   2007
    ## 10 Adelie  Torgersen           42            20.2        190    4250 <NA>   2007
    ## # … with 334 more rows, and abbreviated variable names ¹​flipper_length_mm,
    ## #   ²​body_mass_g

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(pull(penguins,flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

Data in this dataset is about penguins. There are three type of penquins
Adeilie,Chinstrap and Gentoo.These are from an island called Torgersen.

Values are included as bill length, bill depth, flipper length and body
mass , sex, and year.

The number of rows are 344 \` The number of colums are 8 The mean
flipper length is 200.9152

``` r
library(tidyverse)
scatterplot = ggplot(penguins, aes(x = bill_length_mm,
                                   y = flipper_length_mm, 
                                   col = species)) + geom_point()

scatterplot
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_nr2774_1_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
ggsave("HW1scatterplot.pdf", plot = scatterplot )
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

Adelie (species) was indicated as Red dots. Chinstrap (species) was
indicated as green dots. Gentoo (species) was indicated as blue dots.
The graphic shows the clustering of these species at particular space on
the plot.

ggsave comment was to save to scatterplot on PDF from on our file.

# Problem_2

``` r
Data_frame = tibble(
  vec_norm = rnorm(10),
  vec_logical = vec_norm>0,
  vec_char = c("a", "b", "c", "a", "b", "c", "a", "b", "c", "d"),
  vec_factor = factor(c("low", "medium", "high", "low", "medium", "high",
                        "low", "medium", "high", "low"), levels= c( "low", "medium", "high"))
)

Data_frame 
```

    ## # A tibble: 10 × 4
    ##    vec_norm vec_logical vec_char vec_factor
    ##       <dbl> <lgl>       <chr>    <fct>     
    ##  1   2.09   TRUE        a        low       
    ##  2  -1.09   FALSE       b        medium    
    ##  3  -0.0493 FALSE       c        high      
    ##  4  -0.209  FALSE       a        low       
    ##  5   0.692  TRUE        b        medium    
    ##  6  -0.306  FALSE       c        high      
    ##  7   0.0566 TRUE        a        low       
    ##  8  -0.753  FALSE       b        medium    
    ##  9   0.141  TRUE        c        high      
    ## 10   0.812  TRUE        d        low

Data frame was created using tibble function.

``` r
mean(pull(Data_frame, vec_norm))
```

    ## [1] 0.1376434

``` r
mean(pull(Data_frame, vec_logical))
```

    ## [1] 0.5

``` r
mean(pull(Data_frame, vec_char))
```

    ## Warning in mean.default(pull(Data_frame, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(Data_frame, vec_factor))
```

    ## Warning in mean.default(pull(Data_frame, vec_factor)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
as.numeric(pull(Data_frame, vec_norm))
```

    ##  [1]  2.08744703 -1.09454877 -0.04925722 -0.20918301  0.69177419 -0.30645466
    ##  [7]  0.05655564 -0.75280549  0.14111665  0.81178999

``` r
as.numeric(pull(Data_frame, vec_logical))
```

    ##  [1] 1 0 0 0 1 0 1 0 1 1

``` r
as.numeric(pull(Data_frame, vec_char))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(Data_frame, vec_factor))
```

    ##  [1] 1 2 3 1 2 3 1 2 3 1

After using `as.numeric(pull(Data_frame, vec_logical))` for logical
vector it lists the o and 1. When i apply logical factor R supplies
value 0 is signed to false and 1 to true. I allows us to interpret these
values as proportions. For instance, mean for logical was 0.2 that means
2 of the values were true

Appying `as. numeric` command for logical, character and factor
variables, it converts charater values to numeric . So that now R knows
that mean can be calculated were was it was not possible in the previous
mean command. Not the nean of `as.numeric(pull(Data_frame, vec_factor))`
can be calculated where as it was not possible with previous just mean
command.
